# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: curl -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2018-10-01"
  displayName: get metadata url

- script: bash -x ./setup.sh dap
  displayName: 'Run dap and test'